set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/pdk/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/pdk/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper"
set ::env(DESIGN_NAME) "openframe_project_wrapper"
set ::env(VERILOG_FILES) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/rtl/openframe_project_netlists.v /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/rtl/openframe_project_wrapper.v"
set ::env(SYNTH_DEFINES) "PnR"
set ::env(RUN_LINTER) "0"
set ::env(SYNTH_READ_BLACKBOX_LIB) "1"
set ::env(ROUTING_CORES) "10"
set ::env(CLOCK_PERIOD) "25"
set ::env(CLOCK_PORT) "gpio_in\[38]"
set ::env(MACRO_PLACEMENT_CFG) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/macro.cfg"
set ::env(MAGIC_DEF_LABELS) "0"
set ::env(VERILOG_FILES_BLACKBOX) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../picosoc/sky130_sram_2kbyte_1rw1r_32x512_8.v /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/picosoc.v /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/vccd1_connection.v /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/vssd1_connection.v /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/digital_locked_loop.v"
set ::env(EXTRA_LEFS) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../lef/picosoc.lef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../lef/vccd1_connection.lef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../lef/vssd1_connection.lef"
set ::env(EXTRA_GDS_FILES) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../gds/picosoc.gds /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../gds/vccd1_connection.gds /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../gds/vssd1_connection.gds"
set ::env(EXTRA_LIBS) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../lib/picosoc.lib"
set ::env(EXTRA_SPEFS) "picosoc /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.min.spef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.nom.spef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.max.spef digital_locked_loop /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.min.spef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.nom.spef /home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.max.spef"
set ::env(BASE_SDC_FILE) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/base.sdc"
set ::env(RCX_SDC_FILE) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/signoff.sdc"
set ::env(MAX_TRANSITION_CONSTRAINT) "0.5"
set ::env(QUIT_ON_SYNTH_CHECKS) "0"
set ::env(FP_PDN_CHECK_NODES) "0"
set ::env(SYNTH_USE_PG_PINS_DEFINES) "USE_POWER_PINS"
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) "500"
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) "500"
set ::env(CTS_CLK_MAX_WIRE_LENGTH) "500"
set ::env(RUN_CTS) "1"
set ::env(FP_PDN_ENABLE_RAILS) "1"
set ::env(GRT_REPAIR_ANTENNAS) "1"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) "1"
set ::env(FP_PDN_VPITCH) "40"
set ::env(FP_PDN_HPITCH) "40"
set ::env(FP_PDN_VOFFSET) "18.43"
set ::env(FP_PDN_HOFFSET) "22.83"
set ::env(MAGIC_ZEROIZE_ORIGIN) "0"
set ::env(FP_SIZING) "absolute"
set ::env(RUN_CVC) "0"
set ::env(FP_PDN_CORE_RING) "1"
set ::env(FP_PDN_CORE_RING_VWIDTH) "20"
set ::env(FP_PDN_CORE_RING_HWIDTH) "20"
set ::env(FP_PDN_CORE_RING_VOFFSET) "-4"
set ::env(FP_PDN_CORE_RING_HOFFSET) "-4"
set ::env(FP_PDN_CORE_RING_VSPACING) "2.4"
set ::env(FP_PDN_CORE_RING_HSPACING) "2.4"
set ::env(FP_PDN_VWIDTH) "6.4"
set ::env(FP_PDN_HWIDTH) "6.4"
set ::env(FP_PDN_HSPACING) "3.2"
set ::env(FP_PDN_VSPACING) "3.2"
set ::env(VDD_NETS) "vccd1"
set ::env(GND_NETS) "vssd1"
set ::env(PL_TARGET_DENSITY) "0.1"
set ::env(DIE_AREA) "0 0 3166.63 4766.630"
set ::env(CORE_AREA) "40 40 3126.63 4726.630"
set ::env(RUN_IRDROP_REPORT) "0"
set ::env(FP_PDN_MACRO_HOOKS) "openframe_example vccd1 vssd1 VPWR VGND"
set ::env(FP_PDN_CFG) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/pdn_cfg.tcl"
set ::env(FP_DEF_TEMPLATE) "/home/hosni/caravel_openframe_project/openlane/openframe_project_wrapper/fixed_dont_change/openframe_project_wrapper.def"
set ::env(RUN_MAGIC_DRC) "0"
set ::env(RUN_LVS) "0"
