set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/karim/work/pdk/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/karim/work/pdk/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper"
set ::env(DESIGN_NAME) "openframe_project_wrapper"
set ::env(VERILOG_FILES) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/rtl/openframe_project_netlists.v /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/rtl/openframe_project_wrapper.v"
set ::env(RUN_VERILATOR) "0"
set ::env(SYNTH_READ_BLACKBOX_LIB) "1"
set ::env(ROUTING_CORES) "10"
set ::env(CLOCK_PERIOD) "25"
set ::env(CLOCK_PORT) "gpio_in\[38]"
set ::env(MACRO_PLACEMENT_CFG) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/macro.cfg"
set ::env(MAGIC_DEF_LABELS) "0"
set ::env(VERILOG_FILES_BLACKBOX) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/picosoc.v /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../verilog/gl/digital_locked_loop.v"
set ::env(EXTRA_LEFS) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_2kbyte_1rw1r_32x512_8.lef /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../lef/picosoc.lef"
set ::env(EXTRA_GDS_FILES) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_2kbyte_1rw1r_32x512_8.gds /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../gds/picosoc.gds"
set ::env(EXTRA_LIBS) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../lib/picosoc.lib"
set ::env(EXTRA_SPEFS) "picosoc /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.min.spef /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.nom.spef /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/picosoc/openlane-signoff/spef/picosoc.max.spef digital_locked_loop /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.min.spef /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.nom.spef /home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/../../signoff/digital_locked_loop/openlane-signoff/spef/digital_locked_loop.max.spef"
set ::env(BASE_SDC_FILE) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/base.sdc"
set ::env(RCX_SDC_FILE) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/signoff.sdc"
set ::env(QUIT_ON_SYNTH_CHECKS) "0"
set ::env(FP_PDN_CHECK_NODES) "0"
set ::env(SYNTH_USE_PG_PINS_DEFINES) "USE_POWER_PINS"
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) "1"
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) "1000"
set ::env(CTS_CLK_MAX_WIRE_LENGTH) "1000"
set ::env(RUN_CTS) "0"
set ::env(FP_PDN_ENABLE_RAILS) "1"
set ::env(GRT_REPAIR_ANTENNAS) "0"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) "0"
set ::env(FP_PDN_VPITCH) "60"
set ::env(FP_PDN_HPITCH) "60"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(MAGIC_ZEROIZE_ORIGIN) "0"
set ::env(FP_SIZING) "absolute"
set ::env(RUN_CVC) "0"
set ::env(FP_PDN_CORE_RING) "1"
set ::env(FP_PDN_CORE_RING_VWIDTH) "10"
set ::env(FP_PDN_CORE_RING_HWIDTH) "10"
set ::env(FP_PDN_CORE_RING_VOFFSET) "12.45"
set ::env(FP_PDN_CORE_RING_HOFFSET) "12.45"
set ::env(FP_PDN_CORE_RING_VSPACING) "1.6"
set ::env(FP_PDN_CORE_RING_HSPACING) "1.6"
set ::env(FP_PDN_VWIDTH) "6.4"
set ::env(FP_PDN_HWIDTH) "6.4"
set ::env(FP_PDN_HSPACING) "3.2"
set ::env(FP_PDN_VSPACING) "3.2"
set ::env(VDD_NETS) "vccd1"
set ::env(GND_NETS) "vssd1"
set ::env(PL_TARGET_DENSITY) "0.1"
set ::env(DIE_AREA) "0 0 3166.63 4766.630"
set ::env(CORE_AREA) "40 40 3126.63 4726.630"
set ::env(RUN_IRDROP_REPORT) "0"
set ::env(FP_PDN_MACRO_HOOKS) "openframe_example vccd1 vssd1 VPWR VGND"
set ::env(FP_PDN_CFG) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/pdn_cfg.tcl"
set ::env(FP_DEF_TEMPLATE) "/home/karim/work/caravel_openframe_project/openlane/openframe_project_wrapper/fixed_dont_change/openframe_project_wrapper.def"
set ::env(RUN_MAGIC_DRC) "0"
set ::env(RUN_KLAYOUT_XOR) "0"
set ::env(MAGIC_GENERATE_LEF) "0"
set ::env(RUN_LVS) "0"
set ::env(QUIT_ON_HOLD_VIOLATIONS) "0"
