set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/karim/work/pdk/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/karim/work/pdk/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/home/karim/work/caravel_openframe_project/openlane/picosoc"
set ::env(DESIGN_NAME) "picosoc"
set ::env(VERILOG_FILES) "/home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/openframe_project_netlists.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/picosoc.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/picorv32.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/spimemio.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/simpleuart.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/clock_div.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/clock_routing.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/intercon_wb.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/housekeeping.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/simple_spi_master.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/counter_timer_high.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/counter_timer_low.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/mem_wb.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/gpio_wb.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/gpio_vector_wb.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/debug_regs.v"
set ::env(QUIT_ON_VERILATOR_ERRORS) "0"
set ::env(QUIT_ON_SYNTH_CHECKS) "0"
set ::env(SYNTH_READ_BLACKBOX_LIB) "1"
set ::env(ROUTING_CORES) "10"
set ::env(CLOCK_PERIOD) "25"
set ::env(MACRO_PLACEMENT_CFG) "/home/karim/work/caravel_openframe_project/openlane/picosoc/macro.cfg"
set ::env(MAGIC_DEF_LABELS) "0"
set ::env(VERILOG_FILES_BLACKBOX) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v /home/karim/work/caravel_openframe_project/openlane/picosoc/../../verilog/rtl/digital_locked_loop.v"
set ::env(EXTRA_LEFS) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_2kbyte_1rw1r_32x512_8.lef /home/karim/work/caravel_openframe_project/openlane/picosoc/../../lef/digital_locked_loop.lef"
set ::env(EXTRA_GDS_FILES) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_2kbyte_1rw1r_32x512_8.gds /home/karim/work/caravel_openframe_project/openlane/picosoc/../../gds/digital_locked_loop.gds"
set ::env(EXTRA_LIBS) "/home/karim/work/pdk/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib /home/karim/work/caravel_openframe_project/openlane/picosoc/../../lib/digital_locked_loop.lib"
set ::env(STA_MULTICORNER_READ_LIBS) "1"
set ::env(FP_PDN_CHECK_NODES) "0"
set ::env(SYNTH_USE_PG_PINS_DEFINES) "USE_POWER_PINS"
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) "1"
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) "500"
set ::env(FP_PDN_ENABLE_RAILS) "1"
set ::env(FP_PDN_VPITCH) "30"
set ::env(GRT_REPAIR_ANTENNAS) "1"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) "1"
set ::env(GRT_ANT_MARGIN) "20"
set ::env(HEURISTIC_ANTENNA_THRESHOLD) "80"
set ::env(FP_PDN_HPITCH) "40"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(MAGIC_ZEROIZE_ORIGIN) "0"
set ::env(FP_SIZING) "absolute"
set ::env(RUN_CVC) "0"
set ::env(UNIT) "2.4"
set ::env(FP_IO_MODE) "1"
set ::env(FP_IO_VLENGTH) "2.4"
set ::env(FP_IO_HLENGTH) "2.4"
set ::env(FP_PDN_CORE_RING) "0"
set ::env(FP_PDN_VWIDTH) "3.1"
set ::env(FP_PDN_HWIDTH) "3.1"
set ::env(FP_PDN_VSPACING) "2"
set ::env(FP_PDN_HSPACING) "2"
set ::env(FP_PDN_CFG) "/home/karim/work/caravel_openframe_project/openlane/picosoc/pdn_cfg.tcl"
set ::env(FP_PDN_MACRO_HOOKS) "soc_mem\\.mem\\.SRAM_0 VPWR VGND vccd1 vssd1, soc_mem\\.mem\\.SRAM_1 VPWR VGND vccd1 vssd1, dll VPWR VGND vccd1 vssd1"
set ::env(RUN_CTS) "1"
set ::env(CLOCK_PORT) "gpio_in\[38]"
set ::env(PL_TARGET_DENSITY) "0.2"
set ::env(DIE_AREA_WRAPPER) "0 0 3168.82 4768.82"
set ::env(DIE_AREA) "0 0 2200 1400"
set ::env(RUN_IRDROP_REPORT) "0"
set ::env(BASE_SDC_FILE) "/home/karim/work/caravel_openframe_project/openlane/picosoc/base.sdc"
set ::env(GRT_ALLOW_CONGESTION) "1"
set ::env(SYNTH_BUFFERING) "0"
set ::env(RCX_SDC_FILE) "/home/karim/work/caravel_openframe_project/openlane/picosoc/signoff.sdc"
set ::env(RUN_MAGIC_DRC) "0"
set ::env(FP_PIN_ORDER_CFG) "/home/karim/work/caravel_openframe_project/openlane/picosoc/pin_order.cfg"
set ::env(SYNTH_DEFINES) "PnR"
set ::env(QUIT_ON_HOLD_VIOLATIONS) "0"
set ::env(GRT_ADJUSTMENT) "0.08"
